### ISSUE TITLE
Adding a config node to template

### ISSUE THREAD

**Issue by dumdiedum** [alexk111/node-red-node-typescript-starter#2]
Hi there!

Thank you for this repo! Is it possible to add a config node to the blank template? 

Also, I'm new to typescript and yarn, but is it possible to make a Windows-optimized version of package.json (regarding scripts and commands like rm -rf )? Or is there a best practise how to use this on Windows?

**Comment by alexk111** [comment]
Going to add the config node template now.

For the win-optimized version I'd recommend to setup WSL2 on your Windows. This will solve all issues of this kind, once and for all. If it doesn't fit for some reason please create a separate issue for the win compatibility.

**Comment by alexk111** [comment]
Done. Added `config` template.
